name: safesync.io
description: An end-to-end encrypted cloud file storage system.
url: "https://safesync.io"
highlighter: rouge
markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
