title: safesync

name: safesync
description: An end-to-end encrypted cloud file storage system.
url: "https://safesync.reyn.dev"
baseurl: "" # the subpath of your site, e.g. /blog
email: rudy.reyn@gmail.com

github_username:  rudy-reyn

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-spaceship
